Auction/Controllers/LotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Core;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using Auction.BLL.DTOs;
using Auction.BLL.Intefraces;
using Auction.Models.Lot;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Auction.BLL.Exceptions;
using Auction.Filters;

namespace Auction.Controllers
{
    public class LotController:Controller
    {
        private ILotService lotService;


        public LotController(ILotService lotService)
        {
            this.lotService = lotService;
        }

        public ActionResult AutocompleteSearch(string term)
        {
            try
            {
                if (string.IsNullOrEmpty(term))
                {
                    return Json(new { value = "" }, JsonRequestBehavior.AllowGet);
                }
                IEnumerable<LotDTO> lots = lotService.FindByName(term);
                if (lots == null)
                {
                    return Json(new {value = "Can’t find anything"}, JsonRequestBehavior.AllowGet);
                }
                IEnumerable<string> lotNames = lots.Select(l => l.Name).Distinct();
                var models = lotNames.Where(a => a.Contains(term))
                    .Select(a => new {value = a})
                    .Distinct();
               
                return Json(models, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }


        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            LotCreateModel lotModel = new LotCreateModel() { Description = "asf", MainPicturePath = "asf", Name = "asf", Price = 12 };
            lotModel.Datas.AddRange(new List<SelectListItem> {
                new SelectListItem() {Text = "3 days", Value = "3"},
                new SelectListItem() {Text = "7 days", Value = "7"},
                new SelectListItem() {Text = "14 days", Value = "14"},
                new SelectListItem() {Text = "31 days", Value = "31"}
                }
                );
            return View(lotModel);
        }

        [HttpPost]
        [Authorize]
     //   [TimeExpiriedException]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LotCreateModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    LotDTO lot = Mapper.Map<LotDTO>(model);
                    lotService.Create(User.Identity.GetUserId(), Mapper.Map<LotDTO>(model));
                    ModelState.Clear();
                }
                catch (ItemNotExistInDbException)
                {
                    return new HttpStatusCodeResult(400, "Account was removed");
                }
            }
            return View(model);
        }
    }
}

Auction/Views/Shared/_Layout.cshtml
@using Auction.Models.Account
@model Object
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src='@Url.Content("~/Scripts/jquery-1.12.4.js")' type="text/javascript"></script>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/all.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/Layout.css")
    @*@Styles.Render("~/Content/bootstrap-combobox.css")*@
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.js") 
</head>
<body>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>

<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid navbar-border">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand color-green" href="#"><i class="fa fa-home color-green"></i> TradeIt</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li> <a href="#"><i class="fa fa-building"></i> About</a></li>
                    <li><a href="#"><i class="fa fa-phone"></i> Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-anchor"></i> Support <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#"><i class="fa fa-envelope"></i> Email</a></li>
                            <li><a href="#"><i class="fa fa-comments"></i> Chat</a></li>
                            <li><a href="#"><i class="fa fa-phone"></i> Phone Support</a></li>
                            <li class="divider"></li>
                            <li class="active"><a href="#"><i class="fa fa-credit-card"></i> Make a Payment</a></li>
                        </ul>
                    </li>
                    <li>
                        <form class="navbar-form" role="search">
                            <div class="input-group">
                                <input type="text"class ="form-control"name="name" data-autocomplete-source='@Url.Action("AutocompleteSearch", "Lot")'/> 
                                <div class="input-group-btn">    <!-- Categories search  -->
                                    <button type="button" class="btn btn-search btn-default dropdown-toggle br0" data-toggle="dropdown">
                                        <span class="label-icon">Category</span>
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu pull-left" role="menu">
                                        <li>
                                            <a href="#">
                                                <span class="glyphicon glyphicon-user"></span>
                                                <span class="label-icon">Search By User</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">
                                                <span class="glyphicon glyphicon-book"></span>
                                                <span class="label-icon">Search By Organization</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </form>    
                    </li>
                    <li>@Html.ActionLink("Sell now" , "Create", "Lot",routeValues:null ,htmlAttributes: new {@class = "btn" })</li>
                
                </ul>
                @if (Model.GetType() == typeof(LoginModel))
                {
                    @Html.Partial("_LoginPartial", Model)
                }
                else
                {
                    @Html.Partial("_LoginPartial", new LoginModel())
                }
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div class ="body jumbotron">
        @RenderBody();
    </div>
</div>

<script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Scripts/AutocompleteSearch.js")' type="text/javascript"></script>

@RenderSection("scripts", required: false)
ad46D_ewr3
</body>
</html>

Auction/Views/Shared/_SearchPartial.cshtml
@Styles.Render("~/Content/css/Search.css")

<link href="@Url.Content("~/Content/Search.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/themes/base/all.css")" rel="stylesheet" type="text/css" />

<div class="container">
    <div class="row ">
		
        <nav class="navbar navbar-default ">
            <div class="nav nav-justified navbar-nav">
 
                <form class="navbar-form navbar-search search" role="search">
                    <div class="input-group">
                
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-search btn-default dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-search"></span>
                                <span class="label-icon">Search</span>
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu pull-left" role="menu">
                                <li>
                                    <a href="#">
                                        <span class="glyphicon glyphicon-user"></span>
                                        <span class="label-icon">Search By User</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <span class="glyphicon glyphicon-book"></span>
                                        <span class="label-icon">Search By Organization</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
        
                        <input type="text"class ="form-control " name="name" data-autocomplete-source='@Url.Action("AutocompleteSearch", "Lot")'/> 
                        <div class="input-group-btn">
                            <button type="button" class="btn btn-search btn-default" id = "button-search">
                                GO
                            </button>
                         
                         
                        </div>
                    </div>  
                </form>   
         
            </div>
        </nav>
    </div>
</div>

<script type ="text/javascript">
    $(function () {
        $(".input-group-btn .dropdown-menu li a").click(function () {

            var selText = $(this).html();

            //working version - for single button //
            //$('.btn:first-child').html(selText+'<span class="caret"></span>');  

            //working version - for multiple buttons //
            $(this).parents('.input-group-btn').find('.btn-search').html(selText);
        });
    });
</script>
<script src='@Url.Content("~/Scripts/jquery-1.12.4.js")' type="text/javascript"></script>
<script src='@Url.Content("~/Scripts/jquery-ui-1.12.1.js")' type="text/javascript"></script>
@*for autocomplete*@
<script type="text/javascript">
    $(function () {
        $("[data-autocomplete-source]").each(function () {
            var target = $(this);
            target.autocomplete({ source: target.attr("data-autocomplete-source") });
        });
    });
</script>